export const Bookings = [
  {
    heading: "Master JavaScript Basics",
    username: "Alice123",
    details: "A complete journey from zero to hero in JavaScript...",
    board: "CBSE",
    topic: "JavaScript",
    language: "Hindi",
    preferredMode: "Offline",
    address: "Kolkata",
    payment: 2000,
    status: "pending",
    cardId: "JS123",
  },
  {
    heading: "ReactJS Deep Dive",
    username: "DevPro",
    details: "Let's explore advanced React concepts like hooks, context...",
    board: "ICSE",
    topic: "ReactJS",
    language: "English",
    preferredMode: "Online",
    address: "Remote",
    payment: 3000,
    status: "available",
    cardId: "REACT456",
  },
];
export const sampleBookings = [
	{
		cardId: 'BK101',
		tutorName: 'Mr. Rahul Sharma',
		requirements: ['Maths doubt solving', 'Weekly tests'],
		timingSlab: 'Everyday, 5PM - 6PM',
		lastDate: '25 July 2025',
		urgent: true,
		phoneNumber: '9876543210',
	},
	{
		cardId: 'BK102',
		tutorName: 'Ms. Anjali Verma',
		requirements: ['Physics revision'],
		timingSlab: 'Weekends, 10AM - 12PM',
		lastDate: '30 July 2025',
		urgent: false,
		phoneNumber: '9123456780',
	},
	{
		cardId: 'BK103',
		tutorName: 'Dr. Sunil Patil',
		requirements: ['Chemistry basics', 'Assignment help'],
		timingSlab: 'Weekdays, 8PM - 9PM',
		lastDate: '28 July 2025',
		urgent: false,
		phoneNumber: '9999911111',
	},
];